version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: kmrl-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
